---
deployment:
  tasks:
    - export DEPLOYPATH=/home/drazhinb/miniapp/
    - /bin/cp wsgi.py $DEPLOYPATH
    - /bin/cp -R bot/ $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - mkdir -p $DEPLOYPATH/bot-app
    - echo "RewriteEngine On" > $DEPLOYPATH/bot-app/.htaccess
    - echo "RewriteRule ^(.*)$ /wsgi.py [QSA,L]" >> $DEPLOYPATH/bot-app/.htaccess
    - touch $DEPLOYPATH/tmp/restart.txt
