---
deployment:
  tasks:
    - export DEPLOYPATH=/home/drazhinb/miniapp/
    - /bin/cp wsgi.py $DEPLOYPATH
    - /bin/cp -R bot/ $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/bot-app
    - /bin/cat > $DEPLOYPATH/bot-app/.htaccess << 'EOF'
RewriteEngine On
RewriteRule ^(.*)$ /wsgi.py [QSA,L]
EOF
    - touch $DEPLOYPATH/tmp/restart.txt
